// http://www.mathguide.de/info/tools/languagecode.html
const t9n = {
    'de': {
        'Saisonkalender' : 'Saisonkalender',
        'About' : 'Über',
        'Obst' : 'Obst',
        'Gemüse' : 'Gemüse',
        'Salat' : 'Salat',
        'Kräuter' : 'Kräuter',
        // Fruits
        'Apfel': 'Apfel',
        'Aprikose':	'Aprikose',
        'Birne':'Birne',
        'Blaubeeren / Heidelbeeren':	'Blaubeeren / Heidelbeeren',
        'Brombeeren':'Brombeeren',
        'Erdbeeren':	'Erdbeeren',
        'Himbeeren':'Himbeeren',
        'Holunderbeeren / Flieder':	'Holunderbeeren / Flieder',
        'Johannisbeeren': 'Johannisbeeren',
        'Kirschen':'Kirschen',
        'Mirabellen':'Mirabellen',
        'Pflaumen':'Pflaumen',
        'Quitten': 'Quitten',
        'Rhabarber': 'Rhabarber',
        'Stachelbeeren': 'Stachelbeeren',
        'Wassermelonen': 'Wassermelonen',
        'Weintrauben':	'Weintrauben',
        'Zwetschgen': 'Zwetschgen',
        // Vegetables
        'Aubergine': 'Aubergine',
        'Blumenkohl': 'Blumenkohl',
        'Bohnen (grün)': 'Bohnen (grün)',
        'Bohnen (dick)': 'Bohnen (dick)',
        'Brokkoli': 'Brokkoli',
        'Champignons': 'Champignons',
        'Erbsen': 'Erbsen',
        'Fenchel': 'Fenchel',
        'Grünkohl': 'Grünkohl',
        'Gurke (Salatgurke)': 'Gurke (Salatgurke)',
        'Kartoffeln': 'Kartoffeln',
        'Kohlrabi': 'Kohlrabi',
        'Kürbis': 'Kürbis',
        'Lauch (Frühlingszwiebeln)': 'Lauch (Frühlingszwiebeln)',
        'Lauch / Porree': 'Lauch / Porree',
        'Mais': 'Mais',
        'Mangold': 'Mangold',
        'Möhren / Karotten': 'Möhren / Karotten',
        'Paprika': 'Paprika',
        'Pastinaken': 'Pastinaken',
        'Radieschen': 'Radieschen',
        'Rosenkohl': 'Rosenkohl',
        'Rote Bete': 'Rote Bete',
        'Rotkohl': 'Rotkohl',
        'Schwarzwurzeln': 'Schwarzwurzeln',
        'Spargel': 'Spargel',
        'Spinat': 'Spinat',
        'Spitzkohl': 'Spitzkohl',
        'Staudensellerie': 'Staudensellerie',
        'Steckrüben': 'Steckrüben',
        'Tomaten': 'Tomaten',
        'Topinambur': 'Topinambur',
        'Weißkohl': 'Weißkohl',
        'Wirsingkohl': 'Wirsingkohl',
        'Zucchini': 'Zucchini',
        'Zuckerschoten': 'Zuckerschoten',
        'Zwiebeln': 'Zwiebeln',
        // Salad
        'Batavia': 'Batavia',
        'Chicorée': 'Chicorée',
        'Eichblattsalat': 'Eichblattsalat',
        'Eisbergsalat': 'Eisbergsalat',
        'Endiviensalat': 'Endiviensalat',
        'Feldsalat': 'Feldsalat',
        'Kopfsalat': 'Kopfsalat',
        'Lollo Rosso': 'Lollo Rosso',
        'Portulak': 'Portulak',
        'Radicchio': 'Radicchio',
        'Romana': 'Romana',
        'Rucola': 'Rucola',
        // Herbs
        'Dill': 'Dill',
        'Majoran': 'Majoran',
        'Minze': 'Minze',
        'Oregano': 'Oregano',
        'Rosmarin': 'Rosmarin',
        'Schnittlauch': 'Schnittlauch',
        'Thymian':'Thymian',
    },
    'el': {
        'Saisonkalender':'εποχιακό ημερολόγιο',
        'About':'Σχετικά με εμάς',
        'Obst' : 'καρπός',
        'Gemüse' : 'λαχανικό',
        'Salat' : 'σαλάτα',
        'Kräuter' : 'βότανα',
        // Fruits
        'Apfel': 'μήλο',
        'Aprikose':	'βερίκοκο',
        'Birne':'αχλάδι',
        'Blaubeeren / Heidelbeeren':	'μύρτιλα',
        'Brombeeren':'βατόμουρα',
        'Erdbeeren':	'φράουλες',
        'Himbeeren':'σμέουρα',
        'Holunderbeeren / Flieder':	'elderberries',
        'Johannisbeeren': 'κορινθιακή σταφίδα',
        'Kirschen':'κεράσια',
        'Mirabellen':'Mirabelle',
        'Pflaumen':'δαμάσκηνα',
        'Quitten': 'κυδώνι',
        'Rhabarber': 'ραβέντι',
        'Stachelbeeren': 'φραγκοστάφυλα',
        'Wassermelonen': 'καρπούζια',
        'Weintrauben':	'σταφύλια',
        'Zwetschgen': 'δαμάσκηνα',
        // Vegetables
        'Aubergine': 'μελιτζάνα',
        'Blumenkohl': 'κουνουπίδι',
        'Bohnen (grün)': 'Φασόλια πράσινο',
        'Bohnen (dick)': 'φασόλια γίγαντες',
        'Brokkoli': 'μπρόκολο',
        'Champignons': 'μανιτάρια',
        'Erbsen': 'μπιζέλια',
        'Fenchel': 'μάραθο',
        'Grünkohl': 'λάχανο',
        'Gurke (Salatgurke)': 'αγγούρι',
        'Kartoffeln': 'πατάτες',
        'Kohlrabi': 'είδος λάχανου',
        'Kürbis': 'κολοκύθι',
        'Lauch (Frühlingszwiebeln)': 'φρέσκα κρεμμυδάκια',
        'Lauch / Porree': 'πράσο',
        'Mais': 'καλαμπόκι',
        'Mangold': 'σέσκουλα',
        'Möhren / Karotten': 'καρότα',
        'Paprika': 'πάπρικα',
        'Pastinaken': 'παστινάκες',
        'Radieschen': 'ραπανάκι',
        'Rosenkohl': 'λαχανάκια Βρυξελλών',
        'Rote Bete': 'παντζάρια',
        'Rotkohl': 'κόκκινο λάχανο',
        'Schwarzwurzeln': 'τραγοπωλών',
        'Spargel': 'σπαράγγι',
        'Spinat': 'σπανάκι',
        'Spitzkohl': 'λάχανο',
        'Staudensellerie': 'σέλινο',
        'Steckrüben': 'γογγύλια',
        'Tomaten': 'ντομάτες',
        'Topinambur': 'αγκινάρες Ιερουσαλήμ',
        'Weißkohl': 'άσπρο λάχανο',
        'Wirsingkohl': 'λάχανο Μιλάνου',
        'Zucchini': 'κολοκύθι',
        'Zuckerschoten': 'μπιζέλια χιονιού',
        'Zwiebeln': 'κρεμμύδια',
        // Salad
        'Batavia': 'Batavia',
        'Chicorée': 'ραδίκι',
        'Eichblattsalat': 'Eichblattsalat',
        'Eisbergsalat': 'μαρούλι',
        'Endiviensalat': 'αντίδι',
        'Feldsalat': 'λυκοτρίβολο',
        'Kopfsalat': 'μαρούλι',
        'Lollo Rosso': 'Lollo Rosso',
        'Portulak': 'ανδρακλή',
        'Radicchio': 'ραντίτσιο',
        'Romana': 'Romana',
        'Rucola': 'ρόκα',
        // Herbs
        'Dill': 'Dill',
        'Majoran': 'Majoran',
        'Minze': 'Minze',
        'Oregano': 'Oregano',
        'Rosmarin': 'Rosmarin',
        'Schnittlauch': 'Schnittlauch',
        'Thymian':'Thymian',

    },
    'en': {
        'Saisonkalender':'Seasonal Calendar',
        'About':'About',
        'Obst' : 'Fruits',
        'Gemüse' : 'Vegetables',
        'Salat' : 'Salad',
        'Kräuter' : 'Herbs',
        // Fruits
        'Apfel': 'Apple',
        'Aprikose':	'',
        'Birne':'Pear',
        'Blaubeeren / Heidelbeeren':	'blueberry',
        'Brombeeren':'',
        'Erdbeeren':	'strawberry',
        'Himbeeren':'raspberry',
        'Holunderbeeren / Flieder':	'',
        'Johannisbeeren': '',
        'Kirschen':'cherry',
        'Mirabellen':'',
        'Pflaumen':'plums',
        'Quitten': '',
        'Rhabarber': '',
        'Stachelbeeren': '',
        'Wassermelonen': 'melon',
        'Weintrauben':	'grapes',
        'Zwetschgen': '',
        // Vegetables
        'Aubergine': 'eggplant',
        'Blumenkohl': 'Blumenkohl',
        'Bohnen (grün)': 'beans (green)',
        'Bohnen (dick)': 'beans (giant)',
        'Brokkoli': 'Brokkoli',
        'Champignons': 'Champignons',
        'Erbsen': 'Erbsen',
        'Fenchel': 'Fenel',
        'Grünkohl': 'Grünkohl',
        'Gurke (Salatgurke)': 'Gurke (Salatgurke)',
        'Kartoffeln': 'potatoes',
        'Kohlrabi': 'Kohlrabi',
        'Kürbis': 'pumpkin',
        'Lauch (Frühlingszwiebeln)': 'Lauch (Frühlingszwiebeln)',
        'Lauch / Porree': 'Lauch / Porree',
        'Mais': 'corn',
        'Mangold': 'Mangold',
        'Möhren / Karotten': 'Möhren / Karotten',
        'Paprika': 'Paprika',
        'Pastinaken': 'Pastinaken',
        'Radieschen': 'Radieschen',
        'Rosenkohl': 'Rosenkohl',
        'Rote Bete': 'red Bete',
        'Rotkohl': 'Rotkohl',
        'Schwarzwurzeln': 'Schwarzwurzeln',
        'Spargel': 'Spargel',
        'Spinat': 'Spinat',
        'Spitzkohl': 'Spitzkohl',
        'Staudensellerie': 'Staudensellerie',
        'Steckrüben': 'Steckrüben',
        'Tomaten': 'Tomaten',
        'Topinambur': 'Topinambur',
        'Weißkohl': 'cole',
        'Wirsingkohl': 'Wirsingkohl',
        'Zucchini': 'Zucchini',
        'Zuckerschoten': 'Zuckerschoten',
        'Zwiebeln': 'onions',
        // Salad
        'Batavia': 'Batavia',
        'Chicorée': 'Chicorée',
        'Eichblattsalat': 'Eichblattsalat',
        'Eisbergsalat': 'Eisbergsalat',
        'Endiviensalat': 'Endiviensalat',
        'Feldsalat': 'Feldsalat',
        'Kopfsalat': 'Kopfsalat',
        'Lollo Rosso': 'Lollo Rosso',
        'Portulak': 'Portulak',
        'Radicchio': 'Radicchio',
        'Romana': 'Romana',
        'Rucola': 'Rucola',
        // Herbs
        'Dill': 'Dill',
        'Majoran': 'Majoran',
        'Minze': 'Mint',
        'Oregano': 'Oregano',
        'Rosmarin': 'Rosmarin',
        'Schnittlauch': 'Schnittlauch',
        'Thymian':'Thymian',
    },
    'ja': {
        'Saisonkalender':'季節カレンダー',
        'About':'私たちについて',
        'Obst' : 'フルーツ',
        'Gemüse' : '野菜',
        'Salat' : 'サラダ',
        'Kräuter' : 'ハーブ',
        // Fruits
        'Apfel': 'アップル',
        'Aprikose':	'アプリコット',
        'Birne':'梨',
        'Blaubeeren / Heidelbeeren':'ブルーベリー',
        'Brombeeren':'ブラックベリー',
        'Erdbeeren':	'イチゴ',
        'Himbeeren':'ラズベリー',
        'Holunderbeeren / Flieder':	'エルダーベリー',
        'Johannisbeeren': 'スグリ',
        'Kirschen':'チェリー',
        'Mirabellen':'ミラベル',
        'Pflaumen':'プラム',
        'Quitten': '花梨',
        'Rhabarber': 'ルバーブ',
        'Stachelbeeren': 'グーズベリー',
        'Wassermelonen': '西瓜',
        'Weintrauben':	'葡萄',
        'Zwetschgen': 'プラム',
        // Vegetables
        'Aubergine': '茄子',
        'Blumenkohl': 'カリフラワー',
        'Bohnen (grün)': '豆（緑)',
        'Bohnen (dick)': '豆（厚い)',
        'Brokkoli': 'ブロッコリー',
        'Champignons': 'キノコ',
        'Erbsen': 'エンドウ',
        'Fenchel': '茴香',
        'Grünkohl': 'ケール',
        'Gurke (Salatgurke)': '胡瓜',
        'Kartoffeln': 'ジャガイモ',
        'Kohlrabi': 'コールラビ',
        'Kürbis': 'パンプキン',
        'Lauch (Frühlingszwiebeln)': 'ネギ',
        'Lauch / Porree': 'リーキ',
        'Mais': 'コーン',
        'Mangold': 'フダンソウ',
        'Möhren / Karotten': '人参',
        'Paprika': 'パプリカ',
        'Pastinaken': 'パースニップ',
        'Radieschen': 'ラディッシュ',
        'Rosenkohl': '芽キャベツ',
        'Rote Bete': 'ビートルート',
        'Rotkohl': '赤キャベツ',
        'Schwarzwurzeln': 'salsify',
        'Spargel': 'アスパラガス',
        'Spinat': 'ほうれん草',
        'Spitzkohl': 'キャベツ',
        'Staudensellerie': 'セロリ',
        'Steckrüben': 'カブ',
        'Tomaten': 'トマト',
        'Topinambur': 'キクイモ',
        'Weißkohl': 'キャベツ',
        'Wirsingkohl': 'サボイキャベツ',
        'Zucchini': 'ズッキーニ',
        'Zuckerschoten': 'サヤエンドウ',
        'Zwiebeln': '玉葱',
        // Salad
        'Batavia': 'バタビア',
        'Chicorée': 'チコリ',
        'Eichblattsalat': 'Eichblattsalat',
        'Eisbergsalat': 'アイスバーグレタス',
        'Endiviensalat': 'エンダイブ',
        'Feldsalat': '子羊のレタス',
        'Kopfsalat': 'レタス',
        'Lollo Rosso': 'ロロ・ロッソ',
        'Portulak': 'スベリヒユ',
        'Radicchio': '赤チコリ',
        'Romana': 'ロマーナ',
        'Rucola': 'ルッコラ',
        // Herbs
        'Dill': 'ディル',
        'Majoran': 'マヨラナ',
        'Minze': 'ミント',
        'Oregano': 'オレガノ',
        'Rosmarin': 'ローズマリー',
        'Schnittlauch': 'チャイブ',
        'Thymian':'タイム',
    },
    'pl': {
        'Saisonkalender':'Kalendarz sezonowy',
        'About':'O nas',
        'Obst' : 'owoc',
        'Gemüse' : 'warzywo',
        'Salat' : 'sałatka',
        'Kräuter' : 'zioła',
        // Fruits
        'Apfel': 'jabłko',
        'Aprikose':	'',
        'Birne':'',
        'Blaubeeren / Heidelbeeren':	'',
        'Brombeeren':'',
        'Erdbeeren':	'',
        'Himbeeren':'',
        'Holunderbeeren / Flieder':	'',
        'Johannisbeeren': '',
        'Kirschen':'',
        'Mirabellen':'',
        'Pflaumen':'',
        'Quitten': '',
        'Rhabarber': '',
        'Stachelbeeren': '',
        'Wassermelonen': '',
        'Weintrauben':	'',
        'Zwetschgen': '',
        // Vegetables
        'Aubergine': 'Aubergine',
        'Blumenkohl': 'Blumenkohl',
        'Bohnen (grün)': 'Bohnen (grün)',
        'Bohnen (dick)': 'Bohnen (dick)',
        'Brokkoli': 'Brokkoli',
        'Champignons': 'Champignons',
        'Erbsen': 'Erbsen',
        'Fenchel': 'Fenchel',
        'Grünkohl': 'Grünkohl',
        'Gurke (Salatgurke)': 'Gurke (Salatgurke)',
        'Kartoffeln': 'Kartoffeln',
        'Kohlrabi': 'Kohlrabi',
        'Kürbis': 'Kürbis',
        'Lauch (Frühlingszwiebeln)': 'Lauch (Frühlingszwiebeln)',
        'Lauch / Porree': 'Lauch / Porree',
        'Mais': 'Mais',
        'Mangold': 'Mangold',
        'Möhren / Karotten': 'Möhren / Karotten',
        'Paprika': 'Paprika',
        'Pastinaken': 'Pastinaken',
        'Radieschen': 'Radieschen',
        'Rosenkohl': 'Rosenkohl',
        'Rote Bete': 'Rote Bete',
        'Rotkohl': 'Rotkohl',
        'Schwarzwurzeln': 'Schwarzwurzeln',
        'Spargel': 'Spargel',
        'Spinat': 'Spinat',
        'Spitzkohl': 'Spitzkohl',
        'Staudensellerie': 'Staudensellerie',
        'Steckrüben': 'Steckrüben',
        'Tomaten': 'Tomaten',
        'Topinambur': 'Topinambur',
        'Weißkohl': 'Weißkohl',
        'Wirsingkohl': 'Wirsingkohl',
        'Zucchini': 'Zucchini',
        'Zuckerschoten': 'Zuckerschoten',
        'Zwiebeln': 'Zwiebeln',
        // Salad
        'Batavia': 'Batavia',
        'Chicorée': 'Chicorée',
        'Eichblattsalat': 'Eichblattsalat',
        'Eisbergsalat': 'Eisbergsalat',
        'Endiviensalat': 'Endiviensalat',
        'Feldsalat': 'Feldsalat',
        'Kopfsalat': 'Kopfsalat',
        'Lollo Rosso': 'Lollo Rosso',
        'Portulak': 'Portulak',
        'Radicchio': 'Radicchio',
        'Romana': 'Romana',
        'Rucola': 'Rucola',
        // Herbs
        'Dill': 'Dill',
        'Majoran': 'Majoran',
        'Minze': 'Minze',
        'Oregano': 'Oregano',
        'Rosmarin': 'Rosmarin',
        'Schnittlauch': 'Schnittlauch',
        'Thymian':'Thymian',
    },
    'sv': {
        'Saisonkalender':'säsongs kalender',
        'About':'om oss',
        'Obst' : 'frukt',
        'Gemüse' : 'grönsaker',
        'Salat' : 'sallad',
        'Kräuter' : 'örter',
        // Fruits
        'Apfel': 'äpple',
        'Aprikose':	'',
        'Birne':'',
        'Blaubeeren / Heidelbeeren':	'',
        'Brombeeren':'',
        'Erdbeeren':	'',
        'Himbeeren':'',
        'Holunderbeeren / Flieder':	'',
        'Johannisbeeren': '',
        'Kirschen':'',
        'Mirabellen':'',
        'Pflaumen':'',
        'Quitten': '',
        'Rhabarber': '',
        'Stachelbeeren': '',
        'Wassermelonen': '',
        'Weintrauben':	'',
        'Zwetschgen': '',
        // Vegetables
        'Aubergine': 'Aubergine',
        'Blumenkohl': 'Blumenkohl',
        'Bohnen (grün)': 'Bohnen (grün)',
        'Bohnen (dick)': 'Bohnen (dick)',
        'Brokkoli': 'Brokkoli',
        'Champignons': 'Champignons',
        'Erbsen': 'Erbsen',
        'Fenchel': 'Fenchel',
        'Grünkohl': 'Grünkohl',
        'Gurke (Salatgurke)': 'Gurke (Salatgurke)',
        'Kartoffeln': 'Kartoffeln',
        'Kohlrabi': 'Kohlrabi',
        'Kürbis': 'Kürbis',
        'Lauch (Frühlingszwiebeln)': 'Lauch (Frühlingszwiebeln)',
        'Lauch / Porree': 'Lauch / Porree',
        'Mais': 'Mais',
        'Mangold': 'Mangold',
        'Möhren / Karotten': 'Möhren / Karotten',
        'Paprika': 'Paprika',
        'Pastinaken': 'Pastinaken',
        'Radieschen': 'Radieschen',
        'Rosenkohl': 'Rosenkohl',
        'Rote Bete': 'Rote Bete',
        'Rotkohl': 'Rotkohl',
        'Schwarzwurzeln': 'Schwarzwurzeln',
        'Spargel': 'Spargel',
        'Spinat': 'Spinat',
        'Spitzkohl': 'Spitzkohl',
        'Staudensellerie': 'Staudensellerie',
        'Steckrüben': 'Steckrüben',
        'Tomaten': 'Tomaten',
        'Topinambur': 'Topinambur',
        'Weißkohl': 'Weißkohl',
        'Wirsingkohl': 'Wirsingkohl',
        'Zucchini': 'Zucchini',
        'Zuckerschoten': 'Zuckerschoten',
        'Zwiebeln': 'Zwiebeln',
        // Salad
        'Batavia': 'Batavia',
        'Chicorée': 'Chicorée',
        'Eichblattsalat': 'Eichblattsalat',
        'Eisbergsalat': 'Eisbergsalat',
        'Endiviensalat': 'Endiviensalat',
        'Feldsalat': 'Feldsalat',
        'Kopfsalat': 'Kopfsalat',
        'Lollo Rosso': 'Lollo Rosso',
        'Portulak': 'Portulak',
        'Radicchio': 'Radicchio',
        'Romana': 'Romana',
        'Rucola': 'Rucola',
        // Herbs
        'Dill': 'Dill',
        'Majoran': 'Majoran',
        'Minze': 'Minze',
        'Oregano': 'Oregano',
        'Rosmarin': 'Rosmarin',
        'Schnittlauch': 'Schnittlauch',
        'Thymian':'Thymian',
   },

}

const t = (key) => {
  const lang = window.lang || 'de'
  return t9n[lang][key]
}

export default t
