// http://www.mathguide.de/info/tools/languagecode.html
const t9n = {
    'de': {
        'Saisonkalender' : 'Saisonkalender',
        'About' : 'Über',
        'Obst' : 'Obst',
        'Gemüse' : 'Gemüse',
        'Salat' : 'Salat',
        'Kräuter' : 'Kräuter',
        // Fruits
        'Apfel': 'Apfel',
        'Aprikose':	'Aprikose',
        'Birne':'Birne',
        'Blaubeeren / Heidelbeeren':	'Blaubeeren / Heidelbeeren',
        'Brombeeren':'Brombeeren',
        'Erdbeeren':	'Erdbeeren',
        'Himbeeren':'Himbeeren',
        'Holunderbeeren / Flieder':	'Holunderbeeren / Flieder',
        'Johannisbeeren': 'Johannisbeeren',
        'Kirschen':'Kirschen',
        'Mirabellen':'Mirabellen',
        'Pflaumen':'Pflaumen',
        'Quitten': 'Quitten',
        'Rhabarber': 'Rhabarber',
        'Stachelbeeren': 'Stachelbeeren',
        'Wassermelonen': 'Wassermelonen',
        'Weintrauben':	'Weintrauben',
        'Zwetschgen': 'Zwetschgen',
        // Vegetables
        'Aubergine': 'Aubergine',
        'Blumenkohl': 'Blumenkohl',
        'Bohnen (grün)': 'Bohnen (grün)',
        'Bohnen (dick)': 'Bohnen (dick)',
        'Brokkoli': 'Brokkoli',
        'Champignons': 'Champignons',
        'Erbsen': 'Erbsen',
        'Fenchel': 'Fenchel',
        'Grünkohl': 'Grünkohl',
        'Gurke (Salatgurke)': 'Gurke (Salatgurke)',
        'Kartoffeln': 'Kartoffeln',
        'Kohlrabi': 'Kohlrabi',
        'Kürbis': 'Kürbis',
        'Lauch (Frühlingszwieblen)': 'Lauch (Frühlingszwieblen)',
        'Lauch / Porree': 'Lauch / Porree',
        'Mais': 'Mais',
        'Mangold': 'Mangold',
        'Möhren / Karotten': 'Möhren / Karotten',
        'Paprika': 'Paprika',
        'Pastinaken': 'Pastinaken',
        'Radieschen': 'Radieschen',
        'Rosenkohl': 'Rosenkohl',
        'Rote Bete': 'Rote Bete',
        'Rotkohl': 'Rotkohl',
        'Schwarzwurzeln': 'Schwarzwurzeln',
        'Spargel': 'Spargel',
        'Spinat': 'Spinat',
        'Spitzkohl': 'Spitzkohl',
        'Staudensellerie': 'Staudensellerie',
        'Steckrüben': 'Steckrüben',
        'Tomaten': 'Tomaten',
        'Topinambur': 'Topinambur',
        'Weißkohl': 'Weißkohl',
        'Wirsingkohl': 'Wirsingkohl',
        'Zucchini': 'Zucchini',
        'Zuckerschoten': 'Zuckerschoten',
        'Zwiebeln': 'Zwiebeln',
        // Salad
        'Batavia': 'Batavia',
        'Chicorée': 'Chicorée',
        'Eichblattsalat': 'Eichblattsalat',
        'Eisbergsalat': 'Eisbergsalat',
        'Endiviensalat': 'Endiviensalat',
        'Feldsalat': 'Feldsalat',
        'Kopfsalat': 'Kopfsalat',
        'Lollo Rosso': 'Lollo Rosso',
        'Portulak': 'Portulak',
        'Radicchio': 'Radicchio',
        'Romana': 'Romana',
        'Rucola': 'Rucola',
        // Herbs
        'Dill': 'Dill',
        'Majoran': 'Majoran',
        'Minze': 'Minze',
        'Oregano': 'Oregano',
        'Rosmarin': 'Rosmarin',
        'Schnittlauch': 'Schnittlauch',
        'Thymian':'Thymian',
    },
    'el': {
        'Saisonkalender':'εποχιακό ημερολόγιο',
        'About':'Σχετικά με εμάς',
        'Obst' : 'καρπός',
        'Gemüse' : 'λαχανικό',
        'Salat' : 'σαλάτα',
        'Kräuter' : 'βότανα',
        // Fruits
        'Apfel': 'μήλο',
        'Aprikose':	'',
        'Birne':'',
        'Blaubeeren / Heidelbeeren':	'',
        'Brombeeren':'',
        'Erdbeeren':	'',
        'Himbeeren':'',
        'Holunderbeeren / Flieder':	'',
        'Johannisbeeren': '',
        'Kirschen':'',
        'Mirabellen':'',
        'Pflaumen':'',
        'Quitten': '',
        'Rhabarber': '',
        'Stachelbeeren': '',
        'Wassermelonen': '',
        'Weintrauben':	'',
        'Zwetschgen': '',
    },
    'en': {
        'Saisonkalender':'Seasonal Calendar',
        'About':'About',
        'Obst' : 'Fruits',
        'Gemüse' : 'Vegetables',
        'Salat' : 'Salad',
        'Kräuter' : 'Herbs',
        // Fruits
        'Apfel': 'Apple',
        'Aprikose':	'',
        'Birne':'',
        'Blaubeeren / Heidelbeeren':	'',
        'Brombeeren':'',
        'Erdbeeren':	'',
        'Himbeeren':'',
        'Holunderbeeren / Flieder':	'',
        'Johannisbeeren': '',
        'Kirschen':'',
        'Mirabellen':'',
        'Pflaumen':'',
        'Quitten': '',
        'Rhabarber': '',
        'Stachelbeeren': '',
        'Wassermelonen': '',
        'Weintrauben':	'',
        'Zwetschgen': '',
    },
    'ja': {
        'Saisonkalender':'季節カレンダー',
        'About':'私たちについて',
        'Obst' : 'フルーツ',
        'Gemüse' : '野菜',
        'Salat' : 'サラダ',
        'Kräuter' : 'ハーブ',
        // Fruits
        'Apfel': 'アップル',
        'Aprikose':	'アプリコット',
        'Birne':'梨',
        'Blaubeeren / Heidelbeeren':'ブルーベリー',
        'Brombeeren':'ブラックベリー',
        'Erdbeeren':	'イチゴ',
        'Himbeeren':'ラズベリー',
        'Holunderbeeren / Flieder':	'エルダーベリー',
        'Johannisbeeren': 'スグリ',
        'Kirschen':'チェリー',
        'Mirabellen':'ミラベル',
        'Pflaumen':'プラム',
        'Quitten': '花梨',
        'Rhabarber': 'ルバーブ',
        'Stachelbeeren': 'グーズベリー',
        'Wassermelonen': '西瓜',
        'Weintrauben':	'葡萄',
        'Zwetschgen': 'プラム',
    },
    'pl': {
        'Saisonkalender':'Kalendarz sezonowy',
        'About':'O nas',
        'Obst' : 'owoc',
        'Gemüse' : 'warzywo',
        'Salat' : 'sałatka',
        'Kräuter' : 'zioła',
        // Fruits
        'Apfel': 'jabłko',
        'Aprikose':	'',
        'Birne':'',
        'Blaubeeren / Heidelbeeren':	'',
        'Brombeeren':'',
        'Erdbeeren':	'',
        'Himbeeren':'',
        'Holunderbeeren / Flieder':	'',
        'Johannisbeeren': '',
        'Kirschen':'',
        'Mirabellen':'',
        'Pflaumen':'',
        'Quitten': '',
        'Rhabarber': '',
        'Stachelbeeren': '',
        'Wassermelonen': '',
        'Weintrauben':	'',
        'Zwetschgen': '',
    },
    'sv': {
        'Saisonkalender':'säsongs kalender',
        'About':'om oss',
        'Obst' : 'frukt',
        'Gemüse' : 'grönsaker',
        'Salat' : 'sallad',
        'Kräuter' : 'örter',
        // Fruits
        'Apfel': 'äpple',
        'Aprikose':	'',
        'Birne':'',
        'Blaubeeren / Heidelbeeren':	'',
        'Brombeeren':'',
        'Erdbeeren':	'',
        'Himbeeren':'',
        'Holunderbeeren / Flieder':	'',
        'Johannisbeeren': '',
        'Kirschen':'',
        'Mirabellen':'',
        'Pflaumen':'',
        'Quitten': '',
        'Rhabarber': '',
        'Stachelbeeren': '',
        'Wassermelonen': '',
        'Weintrauben':	'',
        'Zwetschgen': '',
   },

}

const t = (key) => {
  const lang = window.lang || 'de'
  return t9n[lang][key]
}

export default t
