// http://www.mathguide.de/info/tools/languagecode.html
const t9n = {
    'de': {
        'Saisonkalender' : 'Saisonkalender',
        'About' : 'Über',
        'Obst' : 'Obst',
        'Gemüse' : 'Gemüse',
        'Salat' : 'Salat',
        'Kräuter' : 'Kräuter',
        // Fruits
        'Apfel': 'Apfel',
        'Aprikose':	'Aprikose',
        'Birne':'Birne',
        'Blaubeeren / Heidelbeeren':	'Blaubeeren / Heidelbeeren',
        'Brombeeren':'Brombeeren',
        'Erdbeeren':	'Erdbeeren',
        'Himbeeren':'Himbeeren',
        'Holunderbeeren / Flieder':	'Holunderbeeren / Flieder',
        'Johannisbeeren': 'Johannisbeeren',
        'Kirschen':'Kirschen',
        'Mirabellen':'Mirabellen',
        'Pflaumen':'Pflaumen',
        'Quitten': 'Quitten',
        'Rhabarber': 'Rhabarber',
        'Stachelbeeren': 'Stachelbeeren',
        'Wassermelonen': 'Wassermelonen',
        'Weintrauben':	'Weintrauben',
        'Zwetschgen': 'Zwetschgen',
        // Vegetables
        'Aubergine': 'Aubergine',
        'Blumenkohl': 'Blumenkohl',
        'Bohnen (grün)': 'Bohnen (grün)',
        'Bohnen (dick)': 'Bohnen (dick)',
        'Brokkoli': 'Brokkoli',
        'Champignons': 'Champignons',
        'Erbsen': 'Erbsen',
        'Fenchel': 'Fenchel',
        'Grünkohl': 'Grünkohl',
        'Gurke (Salatgurke)': 'Gurke (Salatgurke)',
        'Kartoffeln': 'Kartoffeln',
        'Kohlrabi': 'Kohlrabi',
        'Kürbis': 'Kürbis',
        'Lauch (Frühlingszwiebeln)': 'Lauch (Frühlingszwiebeln)',
        'Lauch / Porree': 'Lauch / Porree',
        'Mais': 'Mais',
        'Mangold': 'Mangold',
        'Möhren / Karotten': 'Möhren / Karotten',
        'Paprika': 'Paprika',
        'Pastinaken': 'Pastinaken',
        'Radieschen': 'Radieschen',
        'Rosenkohl': 'Rosenkohl',
        'Rote Bete': 'Rote Bete',
        'Rotkohl': 'Rotkohl',
        'Schwarzwurzeln': 'Schwarzwurzeln',
        'Spargel': 'Spargel',
        'Spinat': 'Spinat',
        'Spitzkohl': 'Spitzkohl',
        'Staudensellerie': 'Staudensellerie',
        'Steckrüben': 'Steckrüben',
        'Tomaten': 'Tomaten',
        'Topinambur': 'Topinambur',
        'Weißkohl': 'Weißkohl',
        'Wirsingkohl': 'Wirsingkohl',
        'Zucchini': 'Zucchini',
        'Zuckerschoten': 'Zuckerschoten',
        'Zwiebeln': 'Zwiebeln',
        // Salad
        'Batavia': 'Batavia',
        'Chicorée': 'Chicorée',
        'Eichblattsalat': 'Eichblattsalat',
        'Eisbergsalat': 'Eisbergsalat',
        'Endiviensalat': 'Endiviensalat',
        'Feldsalat': 'Feldsalat',
        'Kopfsalat': 'Kopfsalat',
        'Lollo Rosso': 'Lollo Rosso',
        'Portulak': 'Portulak',
        'Radicchio': 'Radicchio',
        'Romana': 'Romana',
        'Rucola': 'Rucola',
        // Herbs
        'Dill': 'Dill',
        'Majoran': 'Majoran',
        'Minze': 'Minze',
        'Oregano': 'Oregano',
        'Rosmarin': 'Rosmarin',
        'Schnittlauch': 'Schnittlauch',
        'Thymian':'Thymian',
    },
    'el': {
        'Saisonkalender':'εποχιακό ημερολόγιο',
        'About':'Σχετικά με εμάς',
        'Obst' : 'καρπός',
        'Gemüse' : 'λαχανικό',
        'Salat' : 'σαλάτα',
        'Kräuter' : 'βότανα',
        // Fruits
        'Apfel': 'μήλο',
        'Aprikose':	'βερίκοκο',
        'Birne':'αχλάδι',
        'Blaubeeren / Heidelbeeren':	'μύρτιλα',
        'Brombeeren':'βατόμουρα',
        'Erdbeeren':	'φράουλες',
        'Himbeeren':'σμέουρα',
        'Holunderbeeren / Flieder':	'elderberries',
        'Johannisbeeren': 'κορινθιακή σταφίδα',
        'Kirschen':'κεράσια',
        'Mirabellen':'Mirabelle',
        'Pflaumen':'δαμάσκηνα',
        'Quitten': 'κυδώνι',
        'Rhabarber': 'ραβέντι',
        'Stachelbeeren': 'φραγκοστάφυλα',
        'Wassermelonen': 'καρπούζια',
        'Weintrauben':	'σταφύλια',
        'Zwetschgen': 'δαμάσκηνα',
        // Vegetables
        'Aubergine': 'μελιτζάνα',
        'Blumenkohl': 'κουνουπίδι',
        'Bohnen (grün)': 'Φασόλια πράσινο',
        'Bohnen (dick)': 'φασόλια γίγαντες',
        'Brokkoli': 'μπρόκολο',
        'Champignons': 'μανιτάρια',
        'Erbsen': 'μπιζέλια',
        'Fenchel': 'μάραθο',
        'Grünkohl': 'λάχανο',
        'Gurke (Salatgurke)': 'αγγούρι',
        'Kartoffeln': 'πατάτες',
        'Kohlrabi': 'είδος λάχανου',
        'Kürbis': 'κολοκύθι',
        'Lauch (Frühlingszwiebeln)': 'φρέσκα κρεμμυδάκια',
        'Lauch / Porree': 'πράσο',
        'Mais': 'καλαμπόκι',
        'Mangold': 'σέσκουλα',
        'Möhren / Karotten': 'καρότα',
        'Paprika': 'πάπρικα',
        'Pastinaken': 'παστινάκες',
        'Radieschen': 'ραπανάκι',
        'Rosenkohl': 'λαχανάκια Βρυξελλών',
        'Rote Bete': 'παντζάρια',
        'Rotkohl': 'κόκκινο λάχανο',
        'Schwarzwurzeln': 'τραγοπωλών',
        'Spargel': 'σπαράγγι',
        'Spinat': 'σπανάκι',
        'Spitzkohl': 'λάχανο',
        'Staudensellerie': 'σέλινο',
        'Steckrüben': 'γογγύλια',
        'Tomaten': 'ντομάτες',
        'Topinambur': 'αγκινάρες Ιερουσαλήμ',
        'Weißkohl': 'άσπρο λάχανο',
        'Wirsingkohl': 'λάχανο Μιλάνου',
        'Zucchini': 'κολοκύθι',
        'Zuckerschoten': 'μπιζέλια χιονιού',
        'Zwiebeln': 'κρεμμύδια',
        // Salad
        'Batavia': 'Batavia',
        'Chicorée': 'ραδίκι',
        'Eichblattsalat': 'Eichblattsalat',
        'Eisbergsalat': 'μαρούλι',
        'Endiviensalat': 'αντίδι',
        'Feldsalat': 'λυκοτρίβολο',
        'Kopfsalat': 'μαρούλι',
        'Lollo Rosso': 'Lollo Rosso',
        'Portulak': 'ανδρακλή',
        'Radicchio': 'ραντίτσιο',
        'Romana': 'Romana',
        'Rucola': 'ρόκα',
        // Herbs
        'Dill': 'άνηθο',
        'Majoran': 'μαντζουράνα',
        'Minze': 'μέντα',
        'Oregano': 'ρίγανη',
        'Rosmarin': 'δενδρολίβανο',
        'Schnittlauch': 'βολβοί φαγώσιμοι',
        'Thymian':'θυμάρι',

    },
    'en': {
        'Saisonkalender':'Seasonal Calendar',
        'About':'About',
        'Obst' : 'Fruits',
        'Gemüse' : 'Vegetables',
        'Salat' : 'Salad',
        'Kräuter' : 'Herbs',
        // Fruits
        'Apfel': 'apple',
        'Aprikose':	'apricot',
        'Birne':'pear',
        'Blaubeeren / Heidelbeeren':'blueberry',
        'Brombeeren':'blackberries',
        'Erdbeeren':'strawberry',
        'Himbeeren':'raspberry',
        'Holunderbeeren / Flieder':	'elderberries',
        'Johannisbeeren': 'currants',
        'Kirschen':'cherry',
        'Mirabellen':'Mirabelle',
        'Pflaumen':'plums',
        'Quitten': 'quince',
        'Rhabarber': 'rhubarb',
        'Stachelbeeren': 'gooseberries',
        'Wassermelonen': 'watermelon',
        'Weintrauben':	'grapes',
        'Zwetschgen': 'plums',
        // Vegetables
        'Aubergine': 'eggplant',
        'Blumenkohl': 'cauliflower',
        'Bohnen (grün)': 'beans (green)',
        'Bohnen (dick)': 'beans (giant)',
        'Brokkoli': 'broccoli',
        'Champignons': 'champignons mushrooms',
        'Erbsen': 'peas',
        'Fenchel': 'Fennel',
        'Grünkohl': 'Kale',
        'Gurke (Salatgurke)': 'cucumber',
        'Kartoffeln': 'potatoes',
        'Kohlrabi': 'kohlrabi',
        'Kürbis': 'pumpkin',
        'Lauch (Frühlingszwiebeln)': 'spring onionsLauch',
        'Lauch / Porree': 'leek',
        'Mais': 'corn',
        'Mangold': 'chard',
        'Möhren / Karotten': 'carrots',
        'Paprika': 'pepper',
        'Pastinaken': 'parsnips',
        'Radieschen': 'radish',
        'Rosenkohl': 'brussels sprouts',
        'Rote Bete': 'beetroot',
        'Rotkohl': 'red cabbage',
        'Schwarzwurzeln': 'salsify',
        'Spargel': 'asparagus',
        'Spinat': 'spinach',
        'Spitzkohl': 'cabbage',
        'Staudensellerie': 'celery',
        'Steckrüben': 'turnips',
        'Tomaten': 'tomatoes',
        'Topinambur': 'jerusalem artichokes',
        'Weißkohl': 'white cabbage',
        'Wirsingkohl': 'savoy cabbage',
        'Zucchini': 'zucchini',
        'Zuckerschoten': 'sugar snap',
        'Zwiebeln': 'onions',
        // Salad
        'Batavia': 'batavia',
        'Chicorée': 'chicory',
        'Eichblattsalat': 'eichblatt salad',
        'Eisbergsalat': 'iceberg lettuce',
        'Endiviensalat': 'endive salad',
        'Feldsalat': 'lamb\'s lettuce',
        'Kopfsalat': 'lettuce',
        'Lollo Rosso': 'lollo rosso',
        'Portulak': 'purslane',
        'Radicchio': 'radicchio',
        'Romana': 'romana',
        'Rucola': 'arugula',
        // Herbs
        'Dill': 'dill',
        'Majoran': 'marjoram',
        'Minze': 'mint',
        'Oregano': 'Oregano',
        'Rosmarin': 'rosemary',
        'Schnittlauch': 'chives',
        'Thymian':'thyme',
    },
    'ja': {
        'Saisonkalender':'季節カレンダー',
        'About':'私たちについて',
        'Obst' : 'フルーツ',
        'Gemüse' : '野菜',
        'Salat' : 'サラダ',
        'Kräuter' : 'ハーブ',
        // Fruits
        'Apfel': 'アップル',
        'Aprikose':	'アプリコット',
        'Birne':'梨',
        'Blaubeeren / Heidelbeeren':'ブルーベリー',
        'Brombeeren':'ブラックベリー',
        'Erdbeeren':	'イチゴ',
        'Himbeeren':'ラズベリー',
        'Holunderbeeren / Flieder':	'エルダーベリー',
        'Johannisbeeren': 'スグリ',
        'Kirschen':'チェリー',
        'Mirabellen':'ミラベル',
        'Pflaumen':'プラム',
        'Quitten': '花梨',
        'Rhabarber': 'ルバーブ',
        'Stachelbeeren': 'グーズベリー',
        'Wassermelonen': '西瓜',
        'Weintrauben':	'葡萄',
        'Zwetschgen': 'プラム',
        // Vegetables
        'Aubergine': '茄子',
        'Blumenkohl': 'カリフラワー',
        'Bohnen (grün)': '豆（緑)',
        'Bohnen (dick)': '豆（厚い)',
        'Brokkoli': 'ブロッコリー',
        'Champignons': 'キノコ',
        'Erbsen': 'エンドウ',
        'Fenchel': '茴香',
        'Grünkohl': 'ケール',
        'Gurke (Salatgurke)': '胡瓜',
        'Kartoffeln': 'ジャガイモ',
        'Kohlrabi': 'コールラビ',
        'Kürbis': 'パンプキン',
        'Lauch (Frühlingszwiebeln)': 'ネギ',
        'Lauch / Porree': 'リーキ',
        'Mais': 'コーン',
        'Mangold': 'フダンソウ',
        'Möhren / Karotten': '人参',
        'Paprika': 'パプリカ',
        'Pastinaken': 'パースニップ',
        'Radieschen': 'ラディッシュ',
        'Rosenkohl': '芽キャベツ',
        'Rote Bete': 'ビートルート',
        'Rotkohl': '赤キャベツ',
        'Schwarzwurzeln': 'salsify',
        'Spargel': 'アスパラガス',
        'Spinat': 'ほうれん草',
        'Spitzkohl': 'キャベツ',
        'Staudensellerie': 'セロリ',
        'Steckrüben': 'カブ',
        'Tomaten': 'トマト',
        'Topinambur': 'キクイモ',
        'Weißkohl': 'キャベツ',
        'Wirsingkohl': 'サボイキャベツ',
        'Zucchini': 'ズッキーニ',
        'Zuckerschoten': 'サヤエンドウ',
        'Zwiebeln': '玉葱',
        // Salad
        'Batavia': 'バタビア',
        'Chicorée': 'チコリ',
        'Eichblattsalat': 'Eichblattsalat',
        'Eisbergsalat': 'アイスバーグレタス',
        'Endiviensalat': 'エンダイブ',
        'Feldsalat': '子羊のレタス',
        'Kopfsalat': 'レタス',
        'Lollo Rosso': 'ロロ・ロッソ',
        'Portulak': 'スベリヒユ',
        'Radicchio': '赤チコリ',
        'Romana': 'ロマーナ',
        'Rucola': 'ルッコラ',
        // Herbs
        'Dill': 'ディル',
        'Majoran': 'マヨラナ',
        'Minze': 'ミント',
        'Oregano': 'オレガノ',
        'Rosmarin': 'ローズマリー',
        'Schnittlauch': 'チャイブ',
        'Thymian':'タイム',
    },
    'pl': {
        'Saisonkalender':'Kalendarz sezonowy',
        'About':'O nas',
        'Obst' : 'owoc',
        'Gemüse' : 'warzywo',
        'Salat' : 'sałatka',
        'Kräuter' : 'zioła',
        // Fruits
        'Apfel': 'jabłko',
        'Aprikose':	'morela',
        'Birne':'gruszka',
        'Blaubeeren / Heidelbeeren': 'borówka',
        'Brombeeren':'jeżyny',
        'Erdbeeren':'truskawki',
        'Himbeeren':'maliny',
        'Holunderbeeren / Flieder':	'czarny bez',
        'Johannisbeeren': 'porzeczki',
        'Kirschen':'wiśnie',
        'Mirabellen':'żółta śliwka',
        'Pflaumen':'śliwki',
        'Quitten': 'pigwa',
        'Rhabarber': 'rabarbar',
        'Stachelbeeren': 'agrest',
        'Wassermelonen': 'arbuzy',
        'Weintrauben':	'winogrona',
        'Zwetschgen': 'śliwki',
        // Vegetables
        'Aubergine': 'bakłażan',
        'Blumenkohl': 'kalafior',
        'Bohnen (grün)': 'zielona fasola',
        'Bohnen (dick)': 'fasola (duża)',
        'Brokkoli': 'brokuły',
        'Champignons': 'grzyby',
        'Erbsen': 'groszek',
        'Fenchel': 'koper',
        'Grünkohl': 'jarmuż',
        'Gurke (Salatgurke)': 'ogórek',
        'Kartoffeln': 'ziemniaki',
        'Kohlrabi': 'kalarepa',
        'Kürbis': 'dynia',
        'Lauch (Frühlingszwiebeln)': 'zebula dymka',
        'Lauch / Porree': 'pora',
        'Mais': 'kukurydza',
        'Mangold': 'boćwina',
        'Möhren / Karotten': 'marchew',
        'Paprika': 'papryka',
        'Pastinaken': 'pasternak',
        'Radieschen': 'rzodkiewka',
        'Rosenkohl': 'brukselka',
        'Rote Bete': 'burak ćwikłowy',
        'Rotkohl': 'czerwona kapusta',
        'Schwarzwurzeln': 'salsify',
        'Spargel': 'szparagi',
        'Spinat': 'szpinak',
        'Spitzkohl': 'kapusta',
        'Staudensellerie': 'seler',
        'Steckrüben': 'rzepa',
        'Tomaten': 'pomidory',
        'Topinambur': 'topinambur',
        'Weißkohl': 'kapusta biała',
        'Wirsingkohl': 'kapusta',
        'Zucchini': 'cukinia',
        'Zuckerschoten': 'groszek',
        'Zwiebeln': 'cebule',
        // Salad
        'Batavia': 'batavia',
        'Chicorée': 'cykoria',
        'Eichblattsalat': 'sałatka z eichblatt',
        'Eisbergsalat': 'sałata lodowa',
        'Endiviensalat': 'sałatka z endywii',
        'Feldsalat': 'roszponka',
        'Kopfsalat': 'sałata',
        'Lollo Rosso': 'Lollo Rosso',
        'Portulak': 'portulaka',
        'Radicchio': 'radicchio',
        'Romana': 'Romana',
        'Rucola': 'rukola',
        // Herbs
        'Dill': 'koper',
        'Majoran': 'majeranek',
        'Minze': 'mięta',
        'Oregano': 'oregano',
        'Rosmarin': 'rozmaryn',
        'Schnittlauch': 'szczypiorek',
        'Thymian':'tymianek',
    },
    'sv': {
        'Saisonkalender':'säsongs kalender',
        'About':'om oss',
        'Obst' : 'frukt',
        'Gemüse' : 'grönsaker',
        'Salat' : 'sallad',
        'Kräuter' : 'örter',
        // Fruits
        'Apfel': 'äpple',
        'Aprikose':	'aprikos',
        'Birne':'päron',
        'Blaubeeren / Heidelbeeren':'blåbär',
        'Brombeeren':'björnbär',
        'Erdbeeren':'jordgubbar',
        'Himbeeren':'hallon',
        'Holunderbeeren / Flieder':	'fläderbär',
        'Johannisbeeren': 'vinbär',
        'Kirschen':'körsbär',
        'Mirabellen':'mirabelle',
        'Pflaumen':'plommon',
        'Quitten': 'kvitten',
        'Rhabarber': 'rabarber',
        'Stachelbeeren': 'krusbär',
        'Wassermelonen': 'vattenmeloner',
        'Weintrauben':	'vindruvor',
        'Zwetschgen': 'plommon',
        // Vegetables
        'Aubergine': 'aubergine',
        'Blumenkohl': 'blomkål',
        'Bohnen (grün)': 'bönor (grön)',
        'Bohnen (dick)': 'bönor',
        'Brokkoli': 'broccoli',
        'Champignons': 'svamp',
        'Erbsen': 'ärtor',
        'Fenchel': 'fänkål',
        'Grünkohl': 'grönkål',
        'Gurke (Salatgurke)': 'gurka',
        'Kartoffeln': 'potatis',
        'Kohlrabi': 'kålrabbi',
        'Kürbis': 'pumpa',
        'Lauch (Frühlingszwiebeln)': 'salladslök',
        'Lauch / Porree': 'purjolök',
        'Mais': 'majs',
        'Mangold': 'mangold',
        'Möhren / Karotten': 'morötter',
        'Paprika': 'paprika',
        'Pastinaken': 'palsternacka',
        'Radieschen': 'rädisa',
        'Rosenkohl': 'brysselkål',
        'Rote Bete': 'rödbeta',
        'Rotkohl': 'rödkål',
        'Schwarzwurzeln': 'svartrot',
        'Spargel': 'sparris',
        'Spinat': 'spenat',
        'Spitzkohl': 'spetskål',
        'Staudensellerie': 'selleri',
        'Steckrüben': 'rovor',
        'Tomaten': 'tomater',
        'Topinambur': 'jordärtskockor',
        'Weißkohl': 'vitkål',
        'Wirsingkohl': 'savoykål',
        'Zucchini': 'zucchini',
        'Zuckerschoten': 'snö ärter',
        'Zwiebeln': 'lök',
        // Salad
        'Batavia': 'Batavia',
        'Chicorée': 'cikoria',
        'Eichblattsalat': 'eichblattsallad',
        'Eisbergsalat': 'isbergssallad',
        'Endiviensalat': 'endive',
        'Feldsalat': 'vårklynne',
        'Kopfsalat': 'sallad',
        'Lollo Rosso': 'lollo rosso',
        'Portulak': 'portlak',
        'Radicchio': 'radicchio',
        'Romana': 'romana',
        'Rucola': 'arugula',
        // Herbs
        'Dill': 'dill',
        'Majoran': 'mejram',
        'Minze': 'mint',
        'Oregano': 'oregano',
        'Rosmarin': 'rosmarin',
        'Schnittlauch': 'gräslök',
        'Thymian':'timjan',
   },

}

const t = (key) => {
  const lang = window.lang || 'de'
  return t9n[lang][key]
}

export default t
